### PR TITLE
refactor: change exposed methods and accepted types

### PR DESCRIPTION
**Pull request by jobo322**
BREAKING CHANGE:
- treeSimilarity now only accepts Tree objects
- createTree expects an object {x: [],y: []}

### CODE REVIEW

**Comment by targos** [comment]
The message for the changelog is wrong (breaking change is not the rename of the method). You should remove the `!` from the title and add a `BREAKING CHANGE: ` section with the actual breaking changes.

**Comment by jobo322** [comment]
@targos I have a question about the use of .d.ts to store the types. Is it needed to point to this file in the package.json or is it just enough with the importation in the jsdoc?

**Comment by targos** [comment]
You need to create a `"types"` key in the package.json that points to the file, and also include the file in the distribution (`files` array in package.json).

**Comment by jobo322** [comment]
> The message for the changelog is wrong (breaking change is not the rename of the method). You should remove the `!` from the title and add a `BREAKING CHANGE: ` section with the actual breaking changes.

It is correct now?

**Comment by targos** [comment]
No, please have a look at the message I reworded: https://github.com/mljs/tree-similarity/commit/3ec97d83018b40a55e6048153472fdf9314b1825

- It is not a fix
- We only talk about the breaking changes from the perspective of the end user

**Comment by targos** [comment]
I'm sorry, the format was actually wrong. Here is a new version that works: https://github.com/mljs/tree-similarity/commit/ec9318f470600cf028476ef7b37ed08c3560587d

We cannot have an empty line for `BREAKING CHANGE:`
In general, I think the best way to solve this is to make more than one commit, so each commit has its description and `BREAKING CHANGE:` section.

**Pull request merged**
